### ISSUE TITLE
Hardware Ontology conflicting VANN preferredNamespacePrefix

### ISSUE THREAD

**Issue by keytiong** [oeg-upm/devops-infra#1]
The VANN `preferredNamesapcePrefix` for devoops hardware ontology is the same as the namespace prefix for network ontology. Both ontologies have the preferred prefix defined as `devopsnet`.

This is causing tools that use preferred namespace prefix to shorten IRI to override the conflicting value when using hardware and network ontology together.

One fix is to change the  hardware ontology preferred namespace prefix to `devopshw`.

**Comment by ocorcho** [comment]
Thanks for pointing out. Fixed thanks to your pull request, which has just been accepted.
